export interface Machine {
  id: string; //for DB purpose
  name: string; //name of machine
  type: string; //paneldividing, edge bander, CNC machines, automation, software, accessories
  version: string; //Basic, Professional, Premium
  timeSaving: number; // percentage
  icon: string; //image
  width: number; //width of machine
  height: number; //height of machine
  productivity: number; // units per hour
  machineOperator: number; //number of people required
  connectedLoad: number; //power consumption
  airConsumption: number; //air consumption value
  opex: number; //operational expense
  capex: number; //capital expense
  ROI: number; //by when money recovered (months)
  price: number; //estimated price
}

export interface PlacedMachine extends Machine {
  x: number;
  y: number;
  rotation: number;
  fabricId?: string;
}

export const MACHINE_CATALOG: Machine[] = [
  // ===== PANEL DIVIDING SAWS =====
  {
    id: "pd-001",
    name: "SAWTEQ O-100",
    type: "Panel Dividing",
    version: "Basic",
    timeSaving: 30,
    icon: "🪚",
    width: 3,
    height: 2.5,
    productivity: 45,
    machineOperator: 1,
    connectedLoad: 15,
    airConsumption: 200,
    opex: 2.5,
    capex: 25,
    ROI: 18,
    price: 2500000,
  },
  {
    id: "pd-002",
    name: "SAWTEQ S-100",
    type: "Panel Dividing",
    version: "Professional",
    timeSaving: 40,
    icon: "⚙️",
    width: 3.2,
    height: 2.6,
    productivity: 55,
    machineOperator: 1,
    connectedLoad: 18,
    airConsumption: 220,
    opex: 3,
    capex: 32,
    ROI: 20,
    price: 3200000,
  },
  {
    id: "pd-003",
    name: "SAWTEQ S-180",
    type: "Panel Dividing",
    version: "Premium",
    timeSaving: 50,
    icon: "⚙️",
    width: 3.5,
    height: 2.8,
    productivity: 65,
    machineOperator: 1,
    connectedLoad: 22,
    airConsumption: 250,
    opex: 3.5,
    capex: 38,
    ROI: 22,
    price: 3800000,
  },
  {
    id: "pd-004",
    name: "SAWTEQ S-200",
    type: "Panel Dividing",
    version: "Professional",
    timeSaving: 55,
    icon: "🪚",
    width: 3.8,
    height: 3,
    productivity: 70,
    machineOperator: 2,
    connectedLoad: 25,
    airConsumption: 280,
    opex: 4,
    capex: 42,
    ROI: 24,
    price: 4200000,
  },
  {
    id: "pd-005",
    name: "SAWTEQ S-210",
    type: "Panel Dividing",
    version: "Premium",
    timeSaving: 60,
    icon: "⚙️",
    width: 4,
    height: 3.2,
    productivity: 75,
    machineOperator: 2,
    connectedLoad: 28,
    airConsumption: 300,
    opex: 4.2,
    capex: 45,
    ROI: 24,
    price: 4500000,
  },

  // ===== EDGE BANDERS =====
  {
    id: "eb-001",
    name: "EDGETEQ S-200",
    type: "Edge Bander",
    version: "Basic",
    timeSaving: 35,
    icon: "🧩",
    width: 3,
    height: 2,
    productivity: 40,
    machineOperator: 1,
    connectedLoad: 10,
    airConsumption: 180,
    opex: 2.2,
    capex: 20,
    ROI: 18,
    price: 2000000,
  },
  {
    id: "eb-002",
    name: "EDGETEQ S-230",
    type: "Edge Bander",
    version: "Professional",
    timeSaving: 45,
    icon: "🪵",
    width: 3.2,
    height: 2.2,
    productivity: 55,
    machineOperator: 1,
    connectedLoad: 14,
    airConsumption: 190,
    opex: 2.8,
    capex: 26,
    ROI: 20,
    price: 2600000,
  },
  {
    id: "eb-003",
    name: "EDGETEQ S-240",
    type: "Edge Bander",
    version: "Premium",
    timeSaving: 55,
    icon: "⚙️",
    width: 3.4,
    height: 2.4,
    productivity: 65,
    machineOperator: 1,
    connectedLoad: 16,
    airConsumption: 210,
    opex: 3.1,
    capex: 30,
    ROI: 22,
    price: 3000000,
  },
  {
    id: "eb-004",
    name: "EDGETEQ S-300",
    type: "Edge Bander",
    version: "Professional",
    timeSaving: 60,
    icon: "🪚",
    width: 3.8,
    height: 2.5,
    productivity: 75,
    machineOperator: 2,
    connectedLoad: 18,
    airConsumption: 230,
    opex: 3.5,
    capex: 34,
    ROI: 23,
    price: 3400000,
  },
  {
    id: "eb-005",
    name: "EDGETEQ S-356",
    type: "Edge Bander",
    version: "Premium",
    timeSaving: 65,
    icon: "🧰",
    width: 4,
    height: 2.6,
    productivity: 85,
    machineOperator: 2,
    connectedLoad: 20,
    airConsumption: 250,
    opex: 3.8,
    capex: 38,
    ROI: 24,
    price: 3800000,
  },
  {
    id: "eb-006",
    name: "EDGETEQ S-360",
    type: "Edge Bander",
    version: "Premium",
    timeSaving: 70,
    icon: "⚙️",
    width: 4.2,
    height: 2.8,
    productivity: 95,
    machineOperator: 2,
    connectedLoad: 22,
    airConsumption: 270,
    opex: 4,
    capex: 40,
    ROI: 26,
    price: 4000000,
  },
  {
    id: "eb-007",
    name: "EDGETEQ S-380",
    type: "Edge Bander",
    version: "Premium",
    timeSaving: 75,
    icon: "🔩",
    width: 4.5,
    height: 3,
    productivity: 110,
    machineOperator: 2,
    connectedLoad: 24,
    airConsumption: 300,
    opex: 4.5,
    capex: 45,
    ROI: 28,
    price: 4500000,
  },

  // ===== CNC MACHINES =====
  {
    id: "cnc-001",
    name: "CENTATEQ P-100",
    type: "CNC Machines",
    version: "Basic",
    timeSaving: 40,
    icon: "🔩",
    width: 3.5,
    height: 3,
    productivity: 60,
    machineOperator: 1,
    connectedLoad: 16,
    airConsumption: 220,
    opex: 3.2,
    capex: 35,
    ROI: 22,
    price: 3500000,
  },
  {
    id: "cnc-002",
    name: "CENTATEQ P-110",
    type: "CNC Machines",
    version: "Professional",
    timeSaving: 50,
    icon: "🪵",
    width: 3.8,
    height: 3.2,
    productivity: 70,
    machineOperator: 1,
    connectedLoad: 18,
    airConsumption: 240,
    opex: 3.4,
    capex: 38,
    ROI: 24,
    price: 3800000,
  },
  {
    id: "cnc-003",
    name: "CENTATEQ P-210",
    type: "CNC Machines",
    version: "Professional",
    timeSaving: 60,
    icon: "⚙️",
    width: 4,
    height: 3.4,
    productivity: 80,
    machineOperator: 1,
    connectedLoad: 20,
    airConsumption: 260,
    opex: 3.8,
    capex: 42,
    ROI: 25,
    price: 4200000,
  },
  {
    id: "cnc-004",
    name: "CENTATEQ P-310",
    type: "CNC Machines",
    version: "Premium",
    timeSaving: 65,
    icon: "🤖",
    width: 4.2,
    height: 3.6,
    productivity: 90,
    machineOperator: 2,
    connectedLoad: 24,
    airConsumption: 280,
    opex: 4.2,
    capex: 46,
    ROI: 26,
    price: 4600000,
  },
  {
    id: "cnc-005",
    name: "CENTATEQ P-510",
    type: "CNC Machines",
    version: "Premium",
    timeSaving: 70,
    icon: "🔧",
    width: 4.5,
    height: 3.8,
    productivity: 100,
    machineOperator: 2,
    connectedLoad: 28,
    airConsumption: 320,
    opex: 4.5,
    capex: 50,
    ROI: 28,
    price: 5000000,
  },

  // ===== SOFTWARE =====
  ...[
    "SmartWOP",
    "HOMAG iX",
    "COE",
    "MCS",
    "woodWOP",
    "ControllerMES",
    "MaterialManager",
    "intelliDivide Cutting",
    "Cut Rite optimization software",
  ].map((name, i) => ({
    id: `sw-${i + 1}`,
    name,
    type: "Software",
    version: "Digital",
    timeSaving: 50 + i * 2,
    icon: "💻",
    width: 0,
    height: 0,
    productivity: 0,
    machineOperator: 0,
    connectedLoad: 0,
    airConsumption: 0,
    opex: 0.5,
    capex: 5 + i,
    ROI: 12,
    price: 500000 + i * 50000,
  })),

  // ===== ACCESSORIES =====
  ...[
    "Vaccum cups",
    "Vaccum pump",
    "Cutters",
    "Aggregators",
    "Saw blades",
  ].map((name, i) => ({
    id: `ac-${i + 1}`,
    name,
    type: "Accessories",
    version: "Standard",
    timeSaving: 10 + i * 5,
    icon: "🧰",
    width: 0,
    height: 0,
    productivity: 0,
    machineOperator: 0,
    connectedLoad: 0,
    airConsumption: 0,
    opex: 0.2,
    capex: 2 + i,
    ROI: 6,
    price: 200000 + i * 50000,
  })),

  // ===== AUTOMATION =====
  {
    id: "au-001",
    name: "Conveyors",
    type: "Automation",
    version: "Basic",
    timeSaving: 40,
    icon: "➡️",
    width: 5,
    height: 2,
    productivity: 120,
    machineOperator: 1,
    connectedLoad: 12,
    airConsumption: 150,
    opex: 3,
    capex: 30,
    ROI: 20,
    price: 3000000,
  },
  {
    id: "au-002",
    name: "Return Conveyors",
    type: "Automation",
    version: "Professional",
    timeSaving: 50,
    icon: "🔄",
    width: 5,
    height: 2.2,
    productivity: 130,
    machineOperator: 1,
    connectedLoad: 14,
    airConsumption: 160,
    opex: 3.2,
    capex: 32,
    ROI: 21,
    price: 3200000,
  },
  {
    id: "au-003",
    name: "Panel Loaders",
    type: "Automation",
    version: "Professional",
    timeSaving: 55,
    icon: "🪵",
    width: 5.2,
    height: 2.5,
    productivity: 140,
    machineOperator: 1,
    connectedLoad: 15,
    airConsumption: 170,
    opex: 3.4,
    capex: 35,
    ROI: 22,
    price: 3500000,
  },
  {
    id: "au-004",
    name: "Scissor Lift",
    type: "Automation",
    version: "Premium",
    timeSaving: 60,
    icon: "🛠️",
    width: 3,
    height: 2,
    productivity: 110,
    machineOperator: 1,
    connectedLoad: 10,
    airConsumption: 140,
    opex: 2.5,
    capex: 25,
    ROI: 18,
    price: 2500000,
  },
  {
    id: "au-005",
    name: "Robots",
    type: "Automation",
    version: "Premium",
    timeSaving: 70,
    icon: "🤖",
    width: 3,
    height: 3,
    productivity: 160,
    machineOperator: 1,
    connectedLoad: 20,
    airConsumption: 200,
    opex: 4,
    capex: 40,
    ROI: 24,
    price: 4000000,
  },
];
